/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leftjoin;

import java.util.HashMap;

public class Library {
    /**
     * Gets the left hashMap and Right hashMap and creates a hashMap based on left joins logic
     * @param leftMap
     * @param rightMap
     * @return HashMap
     */
    public HashMap<String, String[]> left_join(HashMap<String, String> leftMap, HashMap<String, String> rightMap) {
        HashMap<String, String[]> finalHashMap = new HashMap<>();

        for(String key: leftMap.keySet()) {
            if(rightMap.containsKey(key)) {
                finalHashMap.put(key,new String[]{leftMap.get(key), rightMap.get(key)});
            } else {
                finalHashMap.put(key, new String[]{leftMap.get(key), null});
            }
        }
        return finalHashMap;
    }

    /**
     * Gets a hashMap of key as String and value as array, and returns a readable format.
     * @param hashmap
     * @return String
     */

    public String readableString(HashMap<String, String[]> hashmap) {
        StringBuilder finalString = new StringBuilder("[\n");

        for (String key: hashmap.keySet()) {
            finalString.append("[ " + "'" + key + "'" + ","
                                    + "'" + hashmap.get(key)[0] + "'" + ","
                                    + "'" + hashmap.get(key)[1] + "'" + "],\n");
        }

        return finalString.append("]\n").toString();

    }
}
