/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package datastructure;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    Library.LinkedList list = new Library.LinkedList();

    //Check to see if empty linked list gets created
    @Test
    public void emptyList() {
        assertEquals("{}", list.toString());
    }

    //Check to see if could be inserted into linked list
    @Test public void checkInsert() {
        list.insert(10);
        list.insert(20);
        list.insert(30);
        list.insert(40);

        System.out.println(list.toString());

        assertEquals("40 30 20 10 ", list.toString());
    }

//    @Test public void emptyList() {
//        Library.LinkedList list = new Library.LinkedList();
//        assertEquals("{}", list.toString());
//    }
//
//    @Test public void emptyList() {
//        Library.LinkedList list = new Library.LinkedList();
//        assertEquals("{}", list.toString());
//    }
//
//    @Test public void emptyList() {
//        Library.LinkedList list = new Library.LinkedList();
//        assertEquals("{}", list.toString());
//    }
}
