/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code401challenges;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testArrayShiftMethod() {
        ArrayShift classUnderTest = new ArrayShift();
        assertArrayEquals("Output should be an array",new int[]{4, 8, 15, 16, 23, 42}, classUnderTest.arrayShift((new int[]{4,8,15,23,42}), 16));

    }
}

